from transformers import pipeline
# Optional - ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Instantiate question-answering transformer
#questions_pipe = pipeline("question-answering", model="deepset/roberta-base-squad2")

#dictionary like this
resources = {"Healthy nails" : """Healthy fingernails are characterized by their smooth texture, absence of pits or grooves, uniform color, and consistent structure.
The anatomy of the fingernail is composed of several distinct parts. The nail plate, the visible hard part of the nail, is primarily made of keratin, a resilient protein also found in hair and the outer layer of skin. Beneath the nail plate is the nail bed, a layer of skin rich in blood vessels that nourish the nail. The cuticle, a protective barrier of tissue, seals the space between the nail plate and the skin, preventing infection. The lunula, the crescent-shaped whitish area at the base of the nail, is part of the matrix where new nail cells are produced.
Healthy fingernails typically do not exhibit abnormalities such as discoloration, spots, or irregularities. Common benign variations include vertical ridges, which may become more prominent with age, and small white spots, often resulting from minor trauma. However, significant changes in nail appearance can signal underlying health issues.
The growth rate of fingernails averages about 3 millimeters per month, though this can vary with age, season, and individual health status. Factors such as nutrition, hormonal changes, and physical activity influence nail growth and health. Adequate intake of proteins, vitamins, and minerals, particularly biotin, vitamin E, and zinc, supports robust nail development.
Regular cleaning and moisturizing can prevent infections and keep nails flexible, which is essential to maintain nail health. Trimming nails straight across and gently rounding the tips helps avoid ingrown nails. It's advisable to avoid biting nails or using them as tools, as these habits can cause damage. The use of protective gloves when engaging in activities that involve prolonged water exposure or harsh chemicals can prevent weakening and brittleness.
Additionally, nail cosmetics and treatments should be used judiciously. While nail polish and other products can enhance the aesthetic appeal of nails, they should be applied and removed correctly to avoid damage. It's important to allow nails to breathe and recover between applications. Furthermore, the overuse of artificial nails and gel treatments can lead to thinning and weakening of the natural nail.
""",

"Clubbing" : """Nail clubbing, also known as digital clubbing or Hippocratic nails, is a deformity of the fingers or toes characterized by changes in the shape and texture of the nails. This condition is often associated with a variety of systemic diseases, primarily affecting the heart and lungs. Nail clubbing is typically identified by the enlargement of the ends of the fingers or toes and the nails becoming abnormally curved and shiny. The nails may also exhibit increased sponginess of the nail bed and loss of the normal angle between the nail and the cuticle.
The symptoms of nail clubbing are gradual and progress through several stages. Initially, there is a softening of the nail bed, making it feel spongy when pressed. This is followed by an increase in the normal 160-degree angle between the nail base and the cuticle, leading to a more pronounced curve of the nail. In advanced stages, the tips of the fingers or toes appear bulbous, and the nails develop a shiny, convex appearance. When nail clubbing occurs in conjunction with joint effusions, joint pains, and abnormal skin and bone growth, it is classified as hypertrophic osteoarthropathy, a condition that warrants further investigation for underlying diseases.
The causes of nail clubbing are diverse and often point to serious underlying health conditions. Pulmonary diseases are among the most common causes, with lung cancer, chronic infections like tuberculosis, and conditions such as cystic fibrosis or bronchiectasis frequently linked to nail clubbing. Cardiovascular diseases, including congenital heart disease, infective endocarditis, and cyanotic heart conditions, can also result in clubbing. Additionally, gastrointestinal disorders such as inflammatory bowel disease, liver cirrhosis, and malabsorption syndromes may present with nail clubbing. Endocrine disorders like hyperthyroidism, acromegaly, and thyroid acropachy are other potential causes. In some cases, nail clubbing occurs without any identifiable underlying disease, a condition known as idiopathic clubbing.
Accurate diagnosis and appropriate treatment of nail clubbing require thorough medical evaluation. This typically involves a detailed patient history, physical examination, and a series of diagnostic tests to identify any underlying systemic conditions. Treatment is primarily focused on addressing the root cause of the clubbing. For instance, if a pulmonary condition is diagnosed, targeted therapies such as antibiotics for infections or specific treatments for lung cancer may be initiated. Similarly, managing cardiovascular or gastrointestinal diseases can lead to the resolution or improvement of nail clubbing.
Preventing nail clubbing involves managing the risk factors and underlying conditions associated with its development. Regular medical check-ups and prompt treatment of respiratory, cardiovascular, and gastrointestinal conditions are essential. Maintaining a healthy lifestyle, including a balanced diet, regular exercise, and avoiding smoking, can also reduce the risk of diseases that may lead to nail clubbing. Early detection and intervention are key to preventing the progression of nail clubbing and its associated complications.
""",

"Terry's nails" : """Terry's nails is a physical condition in which a person's fingernails or toenails appear white with a characteristic "ground glass" appearance, lacking the normal pinkish hue and often without any visible lunula (the crescent-shaped area at the base of the nail). The nails may appear opaque and the distal band of reddish-brown coloration at the tip may be narrow or absent. This condition is generally due to a decrease in vascularity and an increase in connective tissue within the nail bed, leading to the distinctive white appearance.
Terry's nails can indicate various underlying health issues. Liver diseases, such as cirrhosis and hepatitis, are commonly associated with this condition due to the impaired liver function affecting nail health. Chronic kidney failure can also lead to Terry's nails, as the kidneys' reduced efficiency in filtering toxins impacts the body’s vascular and connective tissues. Congestive heart failure is another possible cause, as it compromises circulation, leading to the decreased blood flow to the nails. Diabetes mellitus, especially when poorly controlled, can result in vascular changes that present as Terry's nails. Malnutrition, particularly protein deficiency, and the natural effects of aging can also contribute to the development of this condition. Additionally, chemotherapy can lead to changes in nail appearance, including Terry's nails, due to its impact on rapidly dividing cells and overall health.
Addressing Terry's nails involves identifying and treating the underlying health condition contributing to the nail changes. For instance, managing liver disease through appropriate medications, lifestyle changes, or potentially liver transplantation can improve nail health. Similarly, treating chronic kidney failure with dialysis or kidney transplantation, and managing congestive heart failure with medications and lifestyle modifications, can help alleviate the symptoms of Terry's nails. For diabetes mellitus, strict blood sugar control through diet, exercise, and medications is essential. Ensuring adequate nutrition and addressing any deficiencies can also help improve nail appearance. If chemotherapy is the cause, monitoring and supporting overall health during and after treatment is crucial.
Preventing Terry's nails primarily involves maintaining overall health and managing risk factors for the associated conditions. Regular medical check-ups and early intervention for liver, kidney, and heart diseases are essential. For individuals with diabetes, maintaining tight blood sugar control is crucial. A balanced diet rich in essential nutrients, regular exercise, and avoiding excessive alcohol consumption can support overall health and reduce the risk of conditions that may lead to Terry's nails. For those undergoing chemotherapy, supportive care and monitoring by healthcare providers can help manage and mitigate side effects, including changes in nail health.
""",

"Beau's lines" : """Beau's lines are horizontal indentations or grooves that run across the nailline, contrasting with vertical ridges that extend from the cuticle to the fingertip, which are generally a benign sign of aging. Beau's lines are typically more pronounced and can be felt as a distinct ridge across the nail surface. They indicate a temporary disruption in the growth of the nail plate and can appear on one or more nails simultaneously. The severity of these lines can vary, ranging from shallow to deep grooves, depending on the underlying cause and the extent of the disruption in nail growth.
The formation of Beau's lines is attributed to a temporary cessation of cell division in the nail matrix, the area responsible for producing new nail cells. This interruption in nail growth can result from various factors. Infections, such as severe viral or bacterial infections, can cause a significant enough systemic disturbance to affect nail growth. Trauma to the nail fold, where the nail begins to form, can also lead to the development of Beau's lines. Additionally, systemic illnesses such as high fever, severe malnutrition, or chronic diseases like diabetes and peripheral vascular disease can halt nail production temporarily. Chemotherapy, which targets rapidly dividing cells, including those in the nail matrix, often results in Beau's lines. Other causes include severe stress, major surgeries, or exposure to toxic substances.
There is no specific treatment for Beau's lines themselves, as they are a symptom rather than a condition. The key to addressing Beau's lines lies in identifying and treating the underlying cause. Once the precipitating factor is resolved, normal nail growth will resume, and the lines will eventually grow out and disappear. For instance, if Beau's lines result from an infection, appropriate medical treatment for the infection is necessary. In cases where trauma is the cause, protecting the nail from further injury will allow the nail to heal and grow normally. Managing chronic diseases, maintaining adequate nutrition, and minimizing exposure to stress can also help prevent the recurrence of Beau's lines. Healthcare providers may recommend specific treatments tailored to the underlying condition, ensuring a comprehensive approach to resolving the issue.
Preventing Beau's lines involves maintaining overall health and promptly addressing any conditions that could disrupt nail growth. Regular medical check-ups and early intervention for infections, chronic illnesses, and nutritional deficiencies are essential. Practicing good nail hygiene and protecting nails from trauma can help reduce the risk of physical injuries to the nail matrix. Managing stress through relaxation techniques, regular exercise, and a balanced diet can support overall well-being and prevent disruptions in nail growth. For individuals undergoing chemotherapy or other treatments that may affect nail health, close monitoring and supportive care by healthcare providers can help mitigate the impact on nail growth
""",

"Onychomycosis" : """The most common symptom of onychomycosis is the nail becoming thickened and discolored, often presenting in shades of white, black, yellow, or green. As the fungal infection progresses, the affected nail may become brittle, leading to pieces breaking off or the nail detaching from the nail bed entirely. If left untreated, the surrounding skin can become inflamed, red, and painful, potentially leading to secondary bacterial infections. In severe cases, the nail may develop an unpleasant odor, and the overall appearance of the nail can become severely distorted.
Onychomycosis, also known as tinea unguium, is a fungal infection of the nail caused by various types of fungi, including dermatophytes, yeasts, and non-dermatophyte molds. Dermatophytes are the most common culprits, thriving in warm, moist environments and typically infecting the toenails more frequently than the fingernails. Risk factors for developing onychomycosis include advanced age, compromised immune systems, diabetes, poor peripheral circulation, and a history of athlete’s foot. Environmental factors such as walking barefoot in communal areas like swimming pools, gyms, and locker rooms can also increase the likelihood of contracting the infection.
Onychomycosis does not necessarily require treatment in all cases, particularly if the infection is mild and not causing significant discomfort. However, medical evaluation is essential to determine the severity of the infection and to decide on an appropriate course of action. For more severe or persistent infections, oral antifungal medications, such as terbinafine or itraconazole, are often prescribed. These medications can penetrate the nail and effectively eradicate the infection from within, though they require prolonged use and monitoring for potential side effects. Topical antifungal treatments, although less effective for severe infections, can be useful for milder cases or as an adjunct to oral medications. Regular trimming and thinning of the affected nails, either by the patient or a healthcare professional, can help reduce fungal load and improve the efficacy of topical treatments.
Preventing onychomycosis involves adopting good nail hygiene practices and making lifestyle changes to reduce exposure to fungal pathogens. Keeping nails clean and dry is paramount, as fungi thrive in moist environments. Regularly trimming nails straight across and smoothing the edges can prevent fungal growth and reduce the risk of injury. Disinfecting nail clippers after each use helps prevent the spread of infection. Wearing breathable footwear and moisture-wicking socks can minimize moisture buildup, especially for those prone to sweaty feet. In communal areas, wearing protective footwear such as flip-flops or shower shoes can significantly reduce the risk of contracting the infection. Additionally, avoiding sharing personal items like towels and nail clippers with others can prevent the spread of fungi.
"""
}

def question_pipeline_func (prediction, question):
    questions_pipe = pipeline("question-answering", model="deepset/roberta-base-squad2")
    resources = {"Healthy nails" : """Healthy fingernails are characterized by their smooth texture, absence of pits or grooves, uniform color, and consistent structure.
The anatomy of the fingernail is composed of several distinct parts. The nail plate, the visible hard part of the nail, is primarily made of keratin, a resilient protein also found in hair and the outer layer of skin. Beneath the nail plate is the nail bed, a layer of skin rich in blood vessels that nourish the nail. The cuticle, a protective barrier of tissue, seals the space between the nail plate and the skin, preventing infection. The lunula, the crescent-shaped whitish area at the base of the nail, is part of the matrix where new nail cells are produced.
Healthy fingernails typically do not exhibit abnormalities such as discoloration, spots, or irregularities. Common benign variations include vertical ridges, which may become more prominent with age, and small white spots, often resulting from minor trauma. However, significant changes in nail appearance can signal underlying health issues.
The growth rate of fingernails averages about 3 millimeters per month, though this can vary with age, season, and individual health status. Factors such as nutrition, hormonal changes, and physical activity influence nail growth and health. Adequate intake of proteins, vitamins, and minerals, particularly biotin, vitamin E, and zinc, supports robust nail development.
Regular cleaning and moisturizing can prevent infections and keep nails flexible, which is essential to maintain nail health. Trimming nails straight across and gently rounding the tips helps avoid ingrown nails. It's advisable to avoid biting nails or using them as tools, as these habits can cause damage. The use of protective gloves when engaging in activities that involve prolonged water exposure or harsh chemicals can prevent weakening and brittleness.
Additionally, nail cosmetics and treatments should be used judiciously. While nail polish and other products can enhance the aesthetic appeal of nails, they should be applied and removed correctly to avoid damage. It's important to allow nails to breathe and recover between applications. Furthermore, the overuse of artificial nails and gel treatments can lead to thinning and weakening of the natural nail.
""",

"Clubbing" : """Nail clubbing, also known as digital clubbing or Hippocratic nails, is a deformity of the fingers or toes characterized by changes in the shape and texture of the nails. This condition is often associated with a variety of systemic diseases, primarily affecting the heart and lungs. Nail clubbing is typically identified by the enlargement of the ends of the fingers or toes and the nails becoming abnormally curved and shiny. The nails may also exhibit increased sponginess of the nail bed and loss of the normal angle between the nail and the cuticle.
The symptoms of nail clubbing are gradual and progress through several stages. Initially, there is a softening of the nail bed, making it feel spongy when pressed. This is followed by an increase in the normal 160-degree angle between the nail base and the cuticle, leading to a more pronounced curve of the nail. In advanced stages, the tips of the fingers or toes appear bulbous, and the nails develop a shiny, convex appearance. When nail clubbing occurs in conjunction with joint effusions, joint pains, and abnormal skin and bone growth, it is classified as hypertrophic osteoarthropathy, a condition that warrants further investigation for underlying diseases.
The causes of nail clubbing are diverse and often point to serious underlying health conditions. Pulmonary diseases are among the most common causes, with lung cancer, chronic infections like tuberculosis, and conditions such as cystic fibrosis or bronchiectasis frequently linked to nail clubbing. Cardiovascular diseases, including congenital heart disease, infective endocarditis, and cyanotic heart conditions, can also result in clubbing. Additionally, gastrointestinal disorders such as inflammatory bowel disease, liver cirrhosis, and malabsorption syndromes may present with nail clubbing. Endocrine disorders like hyperthyroidism, acromegaly, and thyroid acropachy are other potential causes. In some cases, nail clubbing occurs without any identifiable underlying disease, a condition known as idiopathic clubbing.
Accurate diagnosis and appropriate treatment of nail clubbing require thorough medical evaluation. This typically involves a detailed patient history, physical examination, and a series of diagnostic tests to identify any underlying systemic conditions. Treatment is primarily focused on addressing the root cause of the clubbing. For instance, if a pulmonary condition is diagnosed, targeted therapies such as antibiotics for infections or specific treatments for lung cancer may be initiated. Similarly, managing cardiovascular or gastrointestinal diseases can lead to the resolution or improvement of nail clubbing.
Preventing nail clubbing involves managing the risk factors and underlying conditions associated with its development. Regular medical check-ups and prompt treatment of respiratory, cardiovascular, and gastrointestinal conditions are essential. Maintaining a healthy lifestyle, including a balanced diet, regular exercise, and avoiding smoking, can also reduce the risk of diseases that may lead to nail clubbing. Early detection and intervention are key to preventing the progression of nail clubbing and its associated complications.
""",

"Terry\'s nail" : """Terry's nails is a physical condition in which a person's fingernails or toenails appear white with a characteristic "ground glass" appearance, lacking the normal pinkish hue and often without any visible lunula (the crescent-shaped area at the base of the nail). The nails may appear opaque and the distal band of reddish-brown coloration at the tip may be narrow or absent. This condition is generally due to a decrease in vascularity and an increase in connective tissue within the nail bed, leading to the distinctive white appearance.
Terry's nails can indicate various underlying health issues. Liver diseases, such as cirrhosis and hepatitis, are commonly associated with this condition due to the impaired liver function affecting nail health. Chronic kidney failure can also lead to Terry's nails, as the kidneys' reduced efficiency in filtering toxins impacts the body’s vascular and connective tissues. Congestive heart failure is another possible cause, as it compromises circulation, leading to the decreased blood flow to the nails. Diabetes mellitus, especially when poorly controlled, can result in vascular changes that present as Terry's nails. Malnutrition, particularly protein deficiency, and the natural effects of aging can also contribute to the development of this condition. Additionally, chemotherapy can lead to changes in nail appearance, including Terry's nails, due to its impact on rapidly dividing cells and overall health.
Addressing Terry's nails involves identifying and treating the underlying health condition contributing to the nail changes. For instance, managing liver disease through appropriate medications, lifestyle changes, or potentially liver transplantation can improve nail health. Similarly, treating chronic kidney failure with dialysis or kidney transplantation, and managing congestive heart failure with medications and lifestyle modifications, can help alleviate the symptoms of Terry's nails. For diabetes mellitus, strict blood sugar control through diet, exercise, and medications is essential. Ensuring adequate nutrition and addressing any deficiencies can also help improve nail appearance. If chemotherapy is the cause, monitoring and supporting overall health during and after treatment is crucial.
Preventing Terry's nails primarily involves maintaining overall health and managing risk factors for the associated conditions. Regular medical check-ups and early intervention for liver, kidney, and heart diseases are essential. For individuals with diabetes, maintaining tight blood sugar control is crucial. A balanced diet rich in essential nutrients, regular exercise, and avoiding excessive alcohol consumption can support overall health and reduce the risk of conditions that may lead to Terry's nails. For those undergoing chemotherapy, supportive care and monitoring by healthcare providers can help manage and mitigate side effects, including changes in nail health.
""",

"Beaus lines" : """Beau's lines are horizontal indentations or grooves that run across the nailline, contrasting with vertical ridges that extend from the cuticle to the fingertip, which are generally a benign sign of aging. Beau's lines are typically more pronounced and can be felt as a distinct ridge across the nail surface. They indicate a temporary disruption in the growth of the nail plate and can appear on one or more nails simultaneously. The severity of these lines can vary, ranging from shallow to deep grooves, depending on the underlying cause and the extent of the disruption in nail growth.
The formation of Beau's lines is attributed to a temporary cessation of cell division in the nail matrix, the area responsible for producing new nail cells. This interruption in nail growth can result from various factors. Infections, such as severe viral or bacterial infections, can cause a significant enough systemic disturbance to affect nail growth. Trauma to the nail fold, where the nail begins to form, can also lead to the development of Beau's lines. Additionally, systemic illnesses such as high fever, severe malnutrition, or chronic diseases like diabetes and peripheral vascular disease can halt nail production temporarily. Chemotherapy, which targets rapidly dividing cells, including those in the nail matrix, often results in Beau's lines. Other causes include severe stress, major surgeries, or exposure to toxic substances.
There is no specific treatment for Beau's lines themselves, as they are a symptom rather than a condition. The key to addressing Beau's lines lies in identifying and treating the underlying cause. Once the precipitating factor is resolved, normal nail growth will resume, and the lines will eventually grow out and disappear. For instance, if Beau's lines result from an infection, appropriate medical treatment for the infection is necessary. In cases where trauma is the cause, protecting the nail from further injury will allow the nail to heal and grow normally. Managing chronic diseases, maintaining adequate nutrition, and minimizing exposure to stress can also help prevent the recurrence of Beau's lines. Healthcare providers may recommend specific treatments tailored to the underlying condition, ensuring a comprehensive approach to resolving the issue.
Preventing Beau's lines involves maintaining overall health and promptly addressing any conditions that could disrupt nail growth. Regular medical check-ups and early intervention for infections, chronic illnesses, and nutritional deficiencies are essential. Practicing good nail hygiene and protecting nails from trauma can help reduce the risk of physical injuries to the nail matrix. Managing stress through relaxation techniques, regular exercise, and a balanced diet can support overall well-being and prevent disruptions in nail growth. For individuals undergoing chemotherapy or other treatments that may affect nail health, close monitoring and supportive care by healthcare providers can help mitigate the impact on nail growth
""",

"Onychomycosis" : """The most common symptom of onychomycosis is the nail becoming thickened and discolored, often presenting in shades of white, black, yellow, or green. As the fungal infection progresses, the affected nail may become brittle, leading to pieces breaking off or the nail detaching from the nail bed entirely. If left untreated, the surrounding skin can become inflamed, red, and painful, potentially leading to secondary bacterial infections. In severe cases, the nail may develop an unpleasant odor, and the overall appearance of the nail can become severely distorted.
Onychomycosis, also known as tinea unguium, is a fungal infection of the nail caused by various types of fungi, including dermatophytes, yeasts, and non-dermatophyte molds. Dermatophytes are the most common culprits, thriving in warm, moist environments and typically infecting the toenails more frequently than the fingernails. Risk factors for developing onychomycosis include advanced age, compromised immune systems, diabetes, poor peripheral circulation, and a history of athlete’s foot. Environmental factors such as walking barefoot in communal areas like swimming pools, gyms, and locker rooms can also increase the likelihood of contracting the infection.
Onychomycosis does not necessarily require treatment in all cases, particularly if the infection is mild and not causing significant discomfort. However, medical evaluation is essential to determine the severity of the infection and to decide on an appropriate course of action. For more severe or persistent infections, oral antifungal medications, such as terbinafine or itraconazole, are often prescribed. These medications can penetrate the nail and effectively eradicate the infection from within, though they require prolonged use and monitoring for potential side effects. Topical antifungal treatments, although less effective for severe infections, can be useful for milder cases or as an adjunct to oral medications. Regular trimming and thinning of the affected nails, either by the patient or a healthcare professional, can help reduce fungal load and improve the efficacy of topical treatments.
Preventing onychomycosis involves adopting good nail hygiene practices and making lifestyle changes to reduce exposure to fungal pathogens. Keeping nails clean and dry is paramount, as fungi thrive in moist environments. Regularly trimming nails straight across and smoothing the edges can prevent fungal growth and reduce the risk of injury. Disinfecting nail clippers after each use helps prevent the spread of infection. Wearing breathable footwear and moisture-wicking socks can minimize moisture buildup, especially for those prone to sweaty feet. In communal areas, wearing protective footwear such as flip-flops or shower shoes can significantly reduce the risk of contracting the infection. Additionally, avoiding sharing personal items like towels and nail clippers with others can prevent the spread of fungi.
"""
}

    answer = questions_pipe(
        question=question,
        context=resources[prediction]

    )['answer']

    return answer
